### PR TITLE
Implement the public `makeobj` and `makeobj!` functions

### PR DESCRIPTION
**Pull request by DilumAluthge**
Fixes https://github.com/quinnj/JSON3.jl/issues/78 

cc: @quinnj

### CODE REVIEW

**Comment by DilumAluthge** [comment]
It looks like `hasfield` requires at least Julia 1.2, so I have updated the Julia `[compat]` requirement in `Project.toml`.

**Comment by DilumAluthge** [comment]
If you don't want to drop support for Julia 1.0 and 1.1 in StructTypes.jl, we could instead put the `makeobj` and `makeobj!` functions in JSON3.jl.

**Comment by DilumAluthge** [comment]
Bump @quinnj

**Comment by quinnj** [comment]
Sorry for the slow response here; I'm bogged down on a few other things and want to do a proper deep dive at the conceptual level here. Going to try and get to this this week

**Pull request closed without merging**
